### ISSUE TITLE
brakuje Panu pliku o nazwie Readme_stud_[index]_rocznik_2020. Praca nie podlega sprawdzeniu.

### ISSUE THREAD

**Issue by OjAntoni** [AbsolutelyVoid/pw_1_lpm9#2]

**Comment by alexesom** [comment]
Hello OjAntoni!
At first I'd like to remind you Sir to write issues in plain Engling again
and I should notice that this repository was created NOT FOR ANY STUDY PURPOSE so there SHOULD BE NO STUDENT README. 
OjAntoni is trolling master of all times. Please be aware.
Cheers. 👎👎👎

**Comment by OjAntoni** [comment]
Odbiło ci już? ALL THE CODE WAS CREATED DURING UNI CLASSES, SO LET'S CONSIDER IT AS A PRODUCT OF POLITECHNIKA WARSZAWSKA, AND NOT "NOT FOR ANY STUDY PURPOSE".
Wzywam Pana do sądu.
Miłego dnia
